openapi: 3.0.3
info:
  title: AnTalk
  description: Мессенджер
  version: 0.0.1

servers:
  - url: https://localhost:8080

tags:
  - name: auth
    description: API для регистрации и входа
  - name: chats
    description: API для работы с чатами
  - name: messages
    description: API для работы с сообщениями

paths:
  /auth/signin:
    post:
      summary: Войти в аккаунт
      operationId: signIn
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignInRequest"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignInResponse"
  /chats:
    post:
      summary: Создание нового чата
      operationId: createChat
      tags:
        - chats
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateChatRequest"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChatDto"
  /messages:
    post:
      summary: Отправка сообщения
      operationId: sendMessage
      tags:
        - messages
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendMessageRequest"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageDto"

components:
  schemas:
    ErrorObject:
      description: Ответ содержащий информацию об ошибке
      type: object
      properties:
        code:
          description: Числовой код ошибки
          type: integer
          format: int32
        message:
          description: Уникальный текстовый идентификатор ошибки
          type: string
        humanMessage:
          description: Человеко-читаемое описание ошибки
          type: string
    SignInRequest:
      description: Запрос на вход в сервис
      type: object
      properties:
        username:
          $ref: "#/components/schemas/userName"
        password:
          $ref: "#/components/schemas/password"
        deviceInfo:
          $ref: "#/components/schemas/deviceInfo"
    SignInResponse:
      description: Ответ на запрос входа в сервис
      type: object
      properties:
        session:
          description: Данные для идентификации сессии (входа на устройстве)
          type: object
          properties:
            id:
              $ref: "#/components/schemas/sessionId"
            token:
              $ref: "#/components/schemas/sessionToken"
    password:
      description: Пароль пользователя
      type: string
    deviceInfo:
      description: Мета-информация об устройстве
      type: object
    sessionId:
      description: Идентификатор сессии (входа на устройстве)
      type: integer
      format: int64
    sessionToken:
      description: Токен сессии
      type: string
    CreateChatRequest:
      description: Запрос на создание чата
      type: object
      properties:
        type:
          $ref: "#/components/schemas/chatType"
        userIds:
          $ref: "#/components/schemas/userIds"
        firstMessage:
          $ref: "#/components/schemas/messageText"
    SendMessageRequest:
      description: Запрос на отправку сообщения
      type: object
      properties:
        senderId:
          $ref: "#/components/schemas/userId"
        chatId:
          $ref: "#/components/schemas/chatId"
        text:
          $ref: "#/components/schemas/messageText"
    UpdateDto:
      description: Обновление
      type: object
      properties:
        id:
          $ref: "#/components/schemas/updateId"
        type:
          $ref: "#/components/schemas/updateType"
        chat:
          $ref: "#/components/schemas/ChatDto"
        message:
          $ref: "#/components/schemas/MessageDto"
    MessageDto:
      description: Сообщение
      type: object
      properties:
        id:
          $ref: "#/components/schemas/messageId"
        user:
          $ref: "#/components/schemas/UserDto"
        chat:
          $ref: "#/components/schemas/ChatDto"
        text:
          $ref: "#/components/schemas/messageText"
    UserDto:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/userId"
        name:
          $ref: "#/components/schemas/userName"
    ChatDto:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/userId"
        type:
          $ref: "#/components/schemas/chatType"
    userIds:
      description: Идентификаторы пользователей
      type: array
      items:
        $ref: "#/components/schemas/userId"
    userId:
      description: Идентификатор пользователя
      type: integer
      format: int64
    userName:
      description: Имя пользователя
      type: string
    chatId:
      description: Идентификатор чата
      type: integer
      format: int64
    chatType:
      description: Тип чата
      type: string
      enum:
        - PRIVATE
    messageId:
      description: Идентификатор сообщения
      type: integer
      format: int64
    messageText:
      description: Текст сообщения
      type: string
    updateId:
      description: Идентификатор обновления
      type: integer
      format: int64
    updateType:
      description: Тип обновления
      type: string
      enum:
        - CHAT_CREATED
        - MESSAGE_SENT
